name: civic_eye_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.1
  geocoding: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  http: ^1.5.0
  fl_chart: ^1.0.0 
  google_maps_flutter: ^2.7.0
  location: ^8.0.1
  google_maps_cluster_manager: ^3.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/track_issue_page_image-removebg-preview.png